[tool.poetry]
name = "zelkey"
version = "0.1.0"
description = "Help find zellig keys"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
